#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadingIconWithAjax
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GeziDB")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGezi_Tablom(Gezi_Tablom instance);
    partial void UpdateGezi_Tablom(Gezi_Tablom instance);
    partial void DeleteGezi_Tablom(Gezi_Tablom instance);
    #endregion
		
		public DBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GeziDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Gezi_Tablom> Gezi_Tabloms
		{
			get
			{
				return this.GetTable<Gezi_Tablom>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gezi_Tablom")]
	public partial class Gezi_Tablom : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _gezi_yer;
		
		private string _gezi_gorsel;
		
		private string _gezi_aciklama;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ongezi_yerChanging(string value);
    partial void Ongezi_yerChanged();
    partial void Ongezi_gorselChanging(string value);
    partial void Ongezi_gorselChanged();
    partial void Ongezi_aciklamaChanging(string value);
    partial void Ongezi_aciklamaChanged();
    #endregion
		
		public Gezi_Tablom()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gezi_yer", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string gezi_yer
		{
			get
			{
				return this._gezi_yer;
			}
			set
			{
				if ((this._gezi_yer != value))
				{
					this.Ongezi_yerChanging(value);
					this.SendPropertyChanging();
					this._gezi_yer = value;
					this.SendPropertyChanged("gezi_yer");
					this.Ongezi_yerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gezi_gorsel", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string gezi_gorsel
		{
			get
			{
				return this._gezi_gorsel;
			}
			set
			{
				if ((this._gezi_gorsel != value))
				{
					this.Ongezi_gorselChanging(value);
					this.SendPropertyChanging();
					this._gezi_gorsel = value;
					this.SendPropertyChanged("gezi_gorsel");
					this.Ongezi_gorselChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gezi_aciklama", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string gezi_aciklama
		{
			get
			{
				return this._gezi_aciklama;
			}
			set
			{
				if ((this._gezi_aciklama != value))
				{
					this.Ongezi_aciklamaChanging(value);
					this.SendPropertyChanging();
					this._gezi_aciklama = value;
					this.SendPropertyChanged("gezi_aciklama");
					this.Ongezi_aciklamaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
